import { layout } from '../../components/layout.js';
import { $,today,esc } from '../../core/utils.js';
import { supabase } from '../../core/supabase.js';

const EXCEL_CATEGORIES=['食費','外食費','軽食費','日用品費','子供関連費','車','学習','保険','通信費','サブスク','ローン','美容','娯楽・趣味','医療','税金','交通費','振替','雑損','雑収入','特別費用','その他費用','給与','賞与','子供手当','臨時収入','その他収入','借入','借入返済'];
const EXCEL_SUMMARIES=[
 ['食材費','expense','食費','normal'],['外食費','expense','外食費','normal'],['軽食費','expense','軽食費','normal'],['日用品','expense','日用品費','normal'],['幼稚園関連費（旭透）','expense','子供関連費','normal'],['子供関連費','expense','子供関連費','normal'],['ガソリン','expense','車','normal'],['学習費','expense','学習','normal'],['保険','expense','保険','normal'],['通信費','expense','通信費','normal'],['サブスク','expense','サブスク','normal'],['DWE','expense','ローン','normal'],['携帯端末分割','expense','ローン','normal'],['美容代','expense','美容','normal'],['娯楽・趣味','expense','娯楽・趣味','normal'],['医療費','expense','医療','normal'],['税金','expense','税金','normal'],['交通費','expense','交通費','normal'],['交通系チャージ（りく）','transfer','振替','charge'],['交通系チャージ（ひま）','transfer','振替','charge'],['ロピア 電子マネーチャージ','transfer','振替','charge'],['現金引出','transfer','振替','transfer'],['現金預入','transfer','振替','transfer'],['口座振替','transfer','振替','transfer'],['三井住友ゴールド引落','expense','振替','card_payment'],['JCB W引落','expense','振替','card_payment'],['三井ショッピングパークカード引落','expense','振替','card_payment'],['テラスモール湘南JCB引落','expense','振替','card_payment'],['JRE ビューカード引落','expense','振替','card_payment'],['Amazonマスター引落','expense','振替','card_payment'],['三井住友NL（向日葵）','expense','振替','card_payment'],['メルカード','expense','振替','card_payment'],['雑損','expense','雑損','normal'],['雑収入','income','雑収入','income'],['特別支出','expense','特別費用','normal'],['その他','expense','その他費用','normal'],['給与①','income','給与','income'],['給与②','income','給与','income'],['賞与','income','賞与','income'],['子供手当','income','子供手当','income'],['臨時収入','income','臨時収入','income'],['立替金','income','その他収入','income'],['父借入','income','借入','borrowing'],['妻借入','income','借入','borrowing'],['父返済','repayment','借入返済','repayment'],['妻返済','repayment','借入返済','repayment'],['その他借入','income','借入','borrowing'],['その他借入返済','repayment','借入返済','repayment']
];

const processLabel={normal:'通常支出',income:'収入',borrowing:'借入',repayment:'返済',transfer:'振替',charge:'チャージ',card_payment:'カード引落'};
const kindLabel={expense:'支出',income:'収入'};

export function renderSettings(s){
 const tpl=(s.settings?.budget_template&&typeof s.settings.budget_template==='object')?s.settings.budget_template:{};
 const templateRows=s.categories.map(x=>`<div class="between" style="gap:10px;margin-top:8px"><span>${esc(x.name)}</span><input type="number" min="0" step="1000" value="${Number(tpl[x.name]||0)||''}" placeholder="未設定" data-template-category="${esc(x.name)}" style="max-width:150px"></div>`).join('');
 const catRows=s.categories.map((x,i)=>`<div class="list-item"><div class="between"><div><b>${esc(x.name)}</b><span class="muted small"> ${esc(kindLabel[x.kind]||x.kind||'')}</span></div><div class="row"><button class="secondary" data-cat-up="${x.id}" ${i===0?'disabled':''}>↑</button><button class="secondary" data-cat-down="${x.id}" ${i===s.categories.length-1?'disabled':''}>↓</button><button class="secondary" data-cat-edit="${x.id}">編集</button><button class="secondary" data-cat-delete="${x.id}">削除</button></div></div></div>`).join('');
 const sumRows=s.summaries.map((x,i)=>`<div class="list-item"><div class="between"><div><b>${esc(x.name)}</b><span class="muted small"> カテゴリ：${esc(x.category_name||'—')} ／ ${esc(processLabel[x.process_type]||x.process_type||'')}</span></div><div class="row"><button class="secondary" data-sum-up="${x.id}" ${i===0?'disabled':''}>↑</button><button class="secondary" data-sum-down="${x.id}" ${i===s.summaries.length-1?'disabled':''}>↓</button><button class="secondary" data-sum-edit="${x.id}">編集</button><button class="secondary" data-sum-delete="${x.id}">削除</button></div></div></div>`).join('');
 const accountRows=s.accounts.map(x=>`<div class="list-item"><div class="between"><div><b>${esc(x.name)}</b><span class="muted small"> ${esc(x.account_type||'')}</span></div><div class="row"><button class="secondary" data-account-edit="${x.id}">編集</button><button class="secondary" data-account-delete="${x.id}">削除</button></div></div><div class="muted small">開始残高 ${Number(x.initial_balance||0).toLocaleString('ja-JP')}円</div></div>`).join('');
 return layout('💰 家計簿OS','settings',`<section class="card"><h2>⚙ 家計設定</h2><p class="muted">カテゴリと摘要（内訳）は別マスタとして管理します。Excelの構成では、例として「子供関連費」カテゴリの下に「幼稚園関連費（旭透）」「子供関連費」などの摘要が紐づきます。</p><div class="grid">
 <section><h3>カテゴリマスタ</h3><p class="muted small">Excel順。↑↓で並べ替え、編集・削除ができます。</p>${catRows||'<p class="muted">カテゴリなし</p>'}<div class="row" style="margin-top:10px"><input id="category-name" placeholder="カテゴリ名"><button class="primary" id="category-save">追加</button></div></section>
 <section><h3>摘要マスタ（内訳）</h3><p class="muted small">摘要ごとにカテゴリ・処理区分を設定。Excelのルールも反映できます。</p>${sumRows||'<p class="muted">摘要なし</p>'}<div class="row" style="margin-top:10px"><input id="summary-name" placeholder="摘要名"><select id="summary-category"><option value="">カテゴリ</option>${s.categories.map(x=>`<option>${esc(x.name)}</option>`).join('')}</select><select id="summary-process"><option value="normal">通常支出</option><option value="income">収入</option><option value="borrowing">借入</option><option value="repayment">返済</option><option value="transfer">振替</option><option value="charge">チャージ</option><option value="card_payment">カード引落</option></select><button class="primary" id="summary-save">追加</button></div></section>
 <section><h3>口座・現金・電子マネー</h3><p class="muted small">資産項目はここで編集・削除できます。削除は履歴を壊さないようアーカイブします。</p>${accountRows||'<p class="muted">資産なし</p>'}<div class="grid" style="margin-top:10px"><input id="account-name" placeholder="名称"><select id="account-type"><option value="bank">口座</option><option value="cash">現金</option><option value="wallet">電子マネー</option><option value="transit">交通系IC</option><option value="other">その他</option></select><input id="account-balance" type="number" value="0" placeholder="開始残高"><button class="primary" id="account-save">追加</button></div></section>
 <section><h3>カード</h3><label>名称</label><input id="card-name" placeholder="JCB W"><div class="grid"><div><label>締め日</label><input id="card-close" type="number" min="1" max="31" value="15"></div><div><label>引落日</label><input id="card-withdraw" type="number" min="1" max="31" value="10"></div></div><label>締め日後の請求月加算</label><input id="card-after" type="number" min="0" value="1"><button class="primary" id="card-save">保存</button></section>
 <section><h3>決済方法</h3><label>名称</label><input id="payment-name" placeholder="現金 / JCB W / Suica"><label>種別</label><select id="payment-type"><option value="cash">現金</option><option value="bank">口座</option><option value="wallet">電子マネー</option><option value="transit">交通系IC</option><option value="card">カード</option><option value="other">その他</option></select><label>連携カード</label><select id="payment-card"><option value="">なし</option>${s.cards.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select><label>連携口座</label><select id="payment-account"><option value="">なし</option>${s.accounts.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select><label>チャージ元設定</label><select id="payment-charge-mode"><option value="each">都度選択</option><option value="fixed">固定</option></select><label>固定チャージ元カード</label><select id="payment-charge-card"><option value="">なし</option>${s.cards.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select><button class="primary" id="payment-save">保存</button></section>
 <section><h3>予算</h3><label>対象年月</label><input id="budget-month" type="month" value="${today().slice(0,7)}"><label>カテゴリ</label><select id="budget-category"><option value="">選択してください</option>${s.categories.map(x=>`<option>${esc(x.name)}</option>`).join('')}</select><label>予算額</label><input id="budget-amount" type="number" min="0" value="0"><button class="primary" id="budget-save">保存</button></section>
 </div></section>
 <section class="card"><h3>Excel準拠の並び</h3><p class="muted small">既存の名称をExcelの順番に並べ替えます。名称自体の追加・削除はしません。</p><div class="row"><button class="secondary" id="excel-category-order">カテゴリをExcel順に</button><button class="secondary" id="excel-summary-order">摘要をExcel順に</button></div></section>
 <section class="card"><h3>毎月の基本予算</h3><p class="muted small">テンプレートとして保存し、「今月に反映」でその月の予算へコピーします。自動繰越はしません。</p>${templateRows||'<p class="muted">先にカテゴリを登録してください。</p>'}<div class="row" style="margin-top:12px"><button class="primary" id="budget-template-save">基本予算を保存</button><button class="secondary" id="budget-template-apply">今月に反映</button></div></section>`)
}

function confirmDelete(label){return window.confirm(`「${label}」を削除します。履歴は残し、マスタから非表示にします。よろしいですか？`)}
async function swapOrder(table,s,id,direction,refresh){const list=table==='category'?[...s.categories]:[...s.summaries];const i=list.findIndex(x=>String(x.id)===String(id));const j=i+direction;if(i<0||j<0||j>=list.length)return;const a=list[i],b=list[j];const{error}=await supabase.from(table==='category'?'household_categories':'household_summaries').upsert([{id:a.id,user_id:s.user.id,sort_order:b.sort_order??j},{id:b.id,user_id:s.user.id,sort_order:a.sort_order??i}],{onConflict:'id'});if(error)return alert(error.message);await refresh('settings')}

export function bindSettings(s,refresh){
 $('category-save')?.addEventListener('click',async()=>{const name=$('category-name').value.trim();if(!name)return alert('カテゴリ名を入力してください');const{error}=await supabase.from('household_categories').insert({user_id:s.user.id,name,kind:'expense',sort_order:s.categories.length,archived:false});if(error)return alert(error.message);await refresh('settings')});
 $('summary-save')?.addEventListener('click',async()=>{const name=$('summary-name').value.trim(),cat=$('summary-category').value,p=$('summary-process').value;if(!name||!cat)return alert('摘要名とカテゴリを入力してください');const cash=['income','borrowing'].includes(p)?'income':['repayment','transfer','charge','card_payment'].includes(p)?'transfer':'expense';const{error}=await supabase.from('household_summaries').insert({user_id:s.user.id,name,category_name:cat,process_type:p,cashflow_type:cash,sort_order:s.summaries.length,archived:false});if(error)return alert(error.message);await refresh('settings')});
 $('account-save')?.addEventListener('click',async()=>{const name=$('account-name').value.trim(),balance=Number($('account-balance').value||0);if(!name)return alert('名称を入力してください');const{error}=await supabase.from('household_accounts').insert({user_id:s.user.id,name,account_type:$('account-type').value,initial_balance:balance,opening_date:today(),archived:false});if(error)return alert(error.message);await refresh('settings')});
 $('card-save')?.addEventListener('click',async()=>{const name=$('card-name').value.trim(),close=Number($('card-close').value),withdraw=Number($('card-withdraw').value),after=Number($('card-after').value);if(!name||close<1||close>31||withdraw<1||withdraw>31||after<0)return alert('カード情報を確認してください');const{error}=await supabase.from('household_cards').upsert({user_id:s.user.id,name,close_day:close,withdrawal_day:withdraw,billing_month_after_close:after,archived:false},{onConflict:'user_id,name'});if(error)return alert(error.message);await refresh('settings')});
 $('payment-save')?.addEventListener('click',async()=>{const name=$('payment-name').value.trim(),type=$('payment-type').value,mode=$('payment-charge-mode').value,fixedCard=$('payment-charge-card').value;if(!name)return alert('決済方法名を入力してください');if(type==='card'&&!$('payment-card').value)return alert('カード決済には連携カードを選択してください');if(['cash','bank','wallet','transit'].includes(type)&&!$('payment-account').value)return alert('この決済方法には連携口座を選択してください');if(['wallet','transit'].includes(type)&&mode==='fixed'&&!fixedCard)return alert('固定チャージ元カードを選択してください');const linkedCard=type==='card'?($('payment-card').value||null):(['wallet','transit'].includes(type)&&mode==='fixed'?(fixedCard||null):null);const{error}=await supabase.from('household_payment_methods').upsert({user_id:s.user.id,name,method_type:type,linked_card_id:linkedCard,linked_account_id:$('payment-account').value||null,archived:false},{onConflict:'user_id,name'});if(error)return alert(error.message);await refresh('settings')});
 $('budget-save')?.addEventListener('click',async()=>{const month=$('budget-month').value,category=$('budget-category').value,amount=Number($('budget-amount').value||0);if(!month||!category||amount<0)return alert('年月・カテゴリ・予算額を確認してください');const{error}=await supabase.from('household_budgets').upsert({user_id:s.user.id,year_month:month+'-01',category_name:category,amount},{onConflict:'user_id,year_month,category_name'});if(error)return alert(error.message);await refresh('settings')});
 $('budget-template-save')?.addEventListener('click',async()=>{const template={};document.querySelectorAll('[data-template-category]').forEach(input=>{const raw=input.value.trim();if(raw!==''){const amount=Number(raw);if(Number.isFinite(amount)&&amount>=0)template[input.dataset.templateCategory]=amount;}});const{error}=await supabase.from('household_settings').upsert({user_id:s.user.id,budget_template:template},{onConflict:'user_id'});if(error)return alert(error.message);await refresh('settings')});
 $('budget-template-apply')?.addEventListener('click',async()=>{const template=(s.settings?.budget_template&&typeof s.settings.budget_template==='object')?s.settings.budget_template:{};const entries=Object.entries(template).filter(([category,amount])=>s.categories.some(c=>c.name===category)&&Number.isFinite(Number(amount))&&Number(amount)>=0);if(!entries.length)return alert('保存済みの基本予算がありません。');const month=(s.settings?.target_year_month||today()).slice(0,7);const payload=entries.map(([category,amount])=>({user_id:s.user.id,year_month:month+'-01',category_name:category,amount:Number(amount)}));const{error}=await supabase.from('household_budgets').upsert(payload,{onConflict:'user_id,year_month,category_name'});if(error)return alert(error.message);await refresh('settings')});
 document.querySelectorAll('[data-cat-up],[data-cat-down]').forEach(btn=>btn.addEventListener('click',()=>swapOrder('category',s,btn.dataset.catUp||btn.dataset.catDown,btn.dataset.catUp?-1:1,refresh)));
 document.querySelectorAll('[data-sum-up],[data-sum-down]').forEach(btn=>btn.addEventListener('click',()=>swapOrder('summary',s,btn.dataset.sumUp||btn.dataset.sumDown,btn.dataset.sumUp?-1:1,refresh)));
 document.querySelectorAll('[data-account-edit]').forEach(btn=>btn.addEventListener('click',async()=>{const a=s.accounts.find(x=>String(x.id)===String(btn.dataset.accountEdit));if(!a)return;const name=prompt('資産名',a.name);if(name===null)return;const type=prompt('種別（bank/cash/wallet/transit/other）',a.account_type||'bank');if(type===null)return;const balance=prompt('開始残高',String(a.initial_balance||0));if(balance===null)return;const{error}=await supabase.from('household_accounts').update({name:name.trim(),account_type:type,initial_balance:Number(balance)}).eq('id',a.id).eq('user_id',s.user.id);if(error)return alert(error.message);await refresh('settings')}));
 document.querySelectorAll('[data-account-delete]').forEach(btn=>btn.addEventListener('click',async()=>{const a=s.accounts.find(x=>String(x.id)===String(btn.dataset.accountDelete));if(!a||!confirmDelete(a.name))return;const{error}=await supabase.from('household_accounts').update({archived:true}).eq('id',a.id).eq('user_id',s.user.id);if(error)return alert(error.message);await refresh('settings')}));
 document.querySelectorAll('[data-cat-edit]').forEach(btn=>btn.addEventListener('click',async()=>{const c=s.categories.find(x=>String(x.id)===String(btn.dataset.catEdit));if(!c)return;const name=prompt('カテゴリ名',c.name);if(name===null||!name.trim())return;const{error}=await supabase.from('household_categories').update({name:name.trim()}).eq('id',c.id).eq('user_id',s.user.id);if(error)return alert(error.message);await supabase.from('household_summaries').update({category_name:name.trim()}).eq('user_id',s.user.id).eq('category_name',c.name);await supabase.from('household_budgets').update({category_name:name.trim()}).eq('user_id',s.user.id).eq('category_name',c.name);await supabase.from('household_transactions').update({category_name:name.trim()}).eq('user_id',s.user.id).eq('category_name',c.name);await refresh('settings')}));
 document.querySelectorAll('[data-cat-delete]').forEach(btn=>btn.addEventListener('click',async()=>{const c=s.categories.find(x=>String(x.id)===String(btn.dataset.catDelete));if(!c||!confirmDelete(c.name))return;const used=s.summaries.some(x=>x.category_name===c.name);if(used)return alert('このカテゴリを使用している摘要があります。先に摘要を削除またはカテゴリ変更してください。');const{error}=await supabase.from('household_categories').update({archived:true}).eq('id',c.id).eq('user_id',s.user.id);if(error)return alert(error.message);await refresh('settings')}));
 document.querySelectorAll('[data-sum-edit]').forEach(btn=>btn.addEventListener('click',async()=>{const x=s.summaries.find(v=>String(v.id)===String(btn.dataset.sumEdit));if(!x)return;const name=prompt('摘要名',x.name);if(name===null||!name.trim())return;const cat=prompt('カテゴリ名',x.category_name||'');if(cat===null||!cat.trim())return;const p=prompt('処理区分（normal/income/borrowing/repayment/transfer/charge/card_payment）',x.process_type||'normal');if(p===null)return;const{error}=await supabase.from('household_summaries').update({name:name.trim(),category_name:cat.trim(),process_type:p}).eq('id',x.id).eq('user_id',s.user.id);if(error)return alert(error.message);await supabase.from('household_transactions').update({summary_name:name.trim(),category_name:cat.trim(),process_type:p}).eq('user_id',s.user.id).eq('summary_id',x.id);await refresh('settings')}));
 document.querySelectorAll('[data-sum-delete]').forEach(btn=>btn.addEventListener('click',async()=>{const x=s.summaries.find(v=>String(v.id)===String(btn.dataset.sumDelete));if(!x||!confirmDelete(x.name))return;const{error}=await supabase.from('household_summaries').update({archived:true}).eq('id',x.id).eq('user_id',s.user.id);if(error)return alert(error.message);await refresh('settings')}));
 $('excel-category-order')?.addEventListener('click',async()=>{const updates=s.categories.map((c,i)=>({id:c.id,user_id:s.user.id,sort_order:EXCEL_CATEGORIES.indexOf(c.name)>=0?EXCEL_CATEGORIES.indexOf(c.name):1000+i}));const{error}=await supabase.from('household_categories').upsert(updates,{onConflict:'id'});if(error)return alert(error.message);await refresh('settings')});
 $('excel-summary-order')?.addEventListener('click',async()=>{const updates=s.summaries.map((x,i)=>({id:x.id,user_id:s.user.id,sort_order:EXCEL_SUMMARIES.findIndex(v=>v[0]===x.name)>=0?EXCEL_SUMMARIES.findIndex(v=>v[0]===x.name):1000+i}));const{error}=await supabase.from('household_summaries').upsert(updates,{onConflict:'id'});if(error)return alert(error.message);await refresh('settings')});
}
