import { layout } from '../../components/layout.js';
import { $,today,yen,esc,billingMonth } from '../../core/utils.js';
import { supabase } from '../../core/supabase.js';
export function renderInput(s){return layout('💰 家計簿OS','input',`<section class="card"><h2>📝 家計を記録</h2><p class="muted small">支出・収入・資産移動・カード引落を区別して記録します。</p><div class="grid"><div><label>取引日</label><input id="tx-date" type="date" value="${today()}"><label>内容</label><input id="tx-desc" placeholder="例：スーパー"><label>摘要</label><select id="tx-summary"><option value="">選択してください</option>${s.summaries.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select><label>決済方法</label><select id="tx-payment"><option value="">選択してください</option>${s.payments.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select><div id="tx-targets"></div></div><div><label>金額</label><input id="tx-amount" type="number" min="1"><label>ポイント利用</label><input id="tx-points" type="number" min="0" value="0"><label>補足</label><input id="tx-target" placeholder="必要な場合だけ入力"><label>メモ</label><input id="tx-memo"></div></div><div id="tx-preview" class="stat" style="margin-top:12px"></div><button id="tx-save" class="primary" style="width:100%;margin-top:12px">この内容で登録</button></section>`)}
export function bindInput(s,refresh){['tx-date','tx-summary','tx-payment','tx-amount','tx-points'].forEach(id=>$(id)?.addEventListener('input',()=>{renderTargets(s);preview(s)}));renderTargets(s);preview(s);$('tx-save')?.addEventListener('click',()=>save(s,refresh))}
function derive(s){const summary=s.summaries.find(x=>x.id===$('tx-summary')?.value),payment=s.payments.find(x=>x.id===$('tx-payment')?.value),card=payment?.linked_card_id?s.cards.find(x=>x.id===payment.linked_card_id):null,account=payment?.linked_account_id?s.accounts.find(x=>x.id===payment.linked_account_id):null,amount=Number($('tx-amount')?.value||0),points=Number($('tx-points')?.value||0),date=$('tx-date')?.value||today(),from=s.accounts.find(x=>x.id===$('tx-from-account')?.value)||null,to=s.accounts.find(x=>x.id===$('tx-to-account')?.value)||null,targetCard=s.cards.find(x=>x.id===$('tx-target-card')?.value)||null;return{summary,payment,card,account,amount,points,date,from,to,targetCard,real:Math.max(0,amount-points),billing:billingMonth(date,card)}}
function optionsAccounts(s,selected=''){return s.accounts.map(x=>`<option value="${x.id}" ${x.id===selected?'selected':''}>${esc(x.name)}</option>`).join('')}
function renderTargets(s){const el=$('tx-targets');if(!el)return;const p=s.summaries.find(x=>x.id===$('tx-summary')?.value)?.process_type;if(p==='card_payment')el.innerHTML=`<label>支払対象カード</label><select id="tx-target-card"><option value="">選択してください</option>${s.cards.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select>`;else if(p==='repayment')el.innerHTML=`<label>返済対象カード</label><select id="tx-target-card"><option value="">なし</option>${s.cards.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select>`;else if(p==='transfer')el.innerHTML=`<label>移動元</label><select id="tx-from-account"><option value="">選択してください</option>${optionsAccounts(s)}</select><label>移動先</label><select id="tx-to-account"><option value="">選択してください</option>${optionsAccounts(s)}</select>`;else el.innerHTML=''}
function preview(s){const x=derive(s);if(!$('tx-preview'))return;let target=x.account?.name||x.card?.name||'—';if(x.summary?.process_type==='transfer')target=`${x.from?.name||'—'} → ${x.to?.name||'—'}`;if(x.summary?.process_type==='card_payment')target=`${x.targetCard?.name||'—'} 引落`;$('tx-preview').innerHTML=`<b>自動判定</b><div class="small">分類：<b>${esc(x.summary?.process_type||'—')}</b> ／ カテゴリ：<b>${esc(x.summary?.category_name||'—')}</b></div><div class="small">反映：<b>${esc(target)}</b> ／ 請求年月：<b>${esc(x.billing||'—')}</b></div><div class="small">金額：<b>${yen(x.amount)}</b> ／ 実決済：<b>${yen(x.real)}</b></div>`}
async function save(s,refresh){const x=derive(s),desc=$('tx-desc').value.trim(),p=x.summary?.process_type;if(!x.summary||!x.payment||!desc||x.amount<=0||x.points<0||x.points>x.amount)return alert('取引日・内容・摘要・決済・金額・ポイントを確認してください。');if(p==='transfer'&&(!x.from||!x.to||x.from.id===x.to.id))return alert('移動元と移動先を確認してください。');if(p==='card_payment'&&!x.targetCard)return alert('支払対象カードを選択してください。');const row={user_id:s.user.id,transaction_date:x.date,description:desc,summary_id:x.summary.id,summary_name:x.summary.name,payment_method_id:x.payment.id,payment_method_name:x.payment.name,amount:x.amount,points_used:x.points,actual_payment:x.real,target_input:$('tx-target').value.trim()||null,target_card_id:x.targetCard?.id||null,from_account_id:x.from?.id||null,to_account_id:x.to?.id||null,memo:$('tx-memo').value.trim()||null,cashflow_type:p==='transfer'?'transfer':x.summary.cashflow_type||'expense',category_name:x.summary.category_name||'その他',process_type:p||'normal',billing_type:x.summary.billing_type||null,billing_card_id:x.card?.id||null,billing_card_name:x.card?.name||null,billing_year_month:x.billing,account_id:x.account?.id||null,effect_amount:p==='transfer'?0:x.real,balance_applied:false};const{error}=await supabase.from('household_transactions').insert(row);if(error)return alert('登録失敗：'+error.message);await refresh('home')}
